language: python
python:
          - '3.5'

before_script:
          - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="project_8.settings"

services:
          - postgresql

script:
          - ./manage.py test
