# Generated by Django 2.2.4 on 2019-11-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'Categories',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(default='', max_length=255)),
                ('nutrition_grade', models.CharField(default='', max_length=255)),
                ('ingredients', models.TextField(default='')),
                ('url', models.TextField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='search.Categories')),
            ],
            options={
                'db_table': 'Products',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
