# Generated by Django 2.2.4 on 2019-10-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_account_substitution'),
    ]

    operations = [
    ]
